language: ruby
rvm:
- 2.4
branches:
  only:
  - stable.05-18
script:
  - jekyll build
install: 
  gem install jekyll 
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
