language: ruby
rvm:
- 2.4
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: rtuFSREdsWLEX1CFyCfbEauAdGISDsl7CCxrdXxkHGLjeq0YWeKaZbk5AxqK3U3HL2haMh9DWGiBO1ztblNiqirHuki7pUglxmGe80l2dFDJ+rd8vXJqctoHNRUzpfAzL5NZMAIkIHPWNFensILgrm7BZ/KA3kXbLaSP4eeBbIwkSoz0XIPFxJ7Wa00JTl9T9qmf2bjt6Tj12vQ3DjvEIij43vfXRBrjzYeJRaJHVCvvwato33yLRq0xH6MIicg2nILIH9jrUQfhYthBQc5DwZ4hubJi0r9flF+sa7UYBe5gep/QWKNunjcMX5rZoGxtyZpWs2zZPgU1Sa5JaVhrtgvTq8VVstOnOZ9TT9yW7RafJRU7FXjxK7wMWFI8Vr2QtSOYigSzNwsdsVhtT/di9ND+H4aZNhxtfXrdExS+KALkU6dOdYM04unAPjB2QPiT8geDgG0kLQhedmADFXPDg7pwFBUpLJXarWpUjNSpgiVOlJvl/jieASlrzC/Ztg9PKT20SvACfkGkgDYSYRbWsO8K77YDnK1iuL+MHdkzcwb1wAy9KPYjDmx6iRll3WUqpH+mE9LIHr37SJGNzLu3/Fb2Eyjkl5IemeqpDsnGQZxshPuQSpHq1TOAzhEEplKl4A0coG/C6pBY+F3zdbfR21FIduKw2tm8h4usAZb7MzM=
  - secure: c+fn0OExjXKngcZ9+6zscKSEyQi3ft8ezy4DUsQX8Qa2imDXMdS/4/N+f50skYSpZv73uuFae8SX15cScTgHwIKOa1XZHkALuHI0A+51HLkIhtBuAAgafLYyKAlpswkvFzjEFxmgi8R5N2s6fXpEyyeYYjPvrx8GHTmT4KZvP6NtLPdTNEcp7GKzNRoXg8ywF03he2c/ZAoLNHAY9ngZqhMfaWH1A8kLRSdxxo00RmvGdf6S1RNdD1cwF+4RCO7sAdtwV59raNHN9F4GTXk3LdQ+Cj/yEV1bI+YA5MBOTPCwYQr+5oDtWwLR7KO8pzD0V7n1ft+Wt7+GfIMnN0URfX0xVceZ8DAR3Z4/6RX/2kshQpKSDHDecXOvW8C4AA5dT0GT+Tw7X/593oHTZ4HCALuGZ2lnh3GwreJcum6aKcup0RzDGe6IUCGDdC2V45sC5nmtVmNmJ2SBZH8P5oVs/9Uzftps5mugv1j95kG2rXRJP5npGBZP4QbWTBgGf/gyfR2KXs6eHSqatVCkRYwQYzAhCnfPXV2WwYn3HspldM4JuCwOeKDlVw+BXIt08L3nvGhyW1L8EaAFe5RvF0NezTMVnUyXBr7HQc+/FUnuzqm1ELxbxfWO+Ok1ypYvfxD8smGT0Qb/SiupzLy2OuC4enUVDbLoRvIgOPwL5TMz1M8=
  - secure: iSYOEC76NOGVouI4gpyo0h+QswQ9wMGr8rb4TQQ2vdaBsf0qoMZdSKLay87dSxDwjDzz+P7/7w7hbqTMM5yZwA3sISMnUt2pnWeThQVwPkuXOyGsLcAY7gZsW5U1EBC96AbuIfDP0QNwkEXHPdUkLMtMeHrxFA0ZghbHsIkLG6Q3IliCvxAeRWkn/o+wvc/Z4SV2RgAdKQo3QtdkwQu3MBq5INf1krzEAKgz7g+C5FFF2w71K/8mqOxFIZi42Lomua/Cp1PsYVchVuhDWKHrP7flxv1Xsh57jjfiJ2efMNY0BAnr3SMv/f/QNiHolsaV+jglHrd57dtV14Qn95nvpjkzCgVHYqN2ez6XLEXkknwqrf1fbOzh/1ymTipUAgZW1mqFW4Mr4UuhDu2aiB4kSeUSl3v9JbYif0SUDbN3vy0KwW8DVR43WLJAtjGrAQVuoOCupkN5pokEffPfsc/fvsbk9Bko+RhLcpjlgdEe0jmJTOB1IyA76Zr4R46R9xNtFuRgeaASTUfIVWdy41i3oYYQfFrr04LL6xv8F9JZL9owidXiRITqwfgVWMko/Gq5PlQh56WNH1sWnjOXf0Oz0k/tUT98l+gwGqLdcpqW0wpXUjFjdOuqM2nuZyuNkTKEmXITQi68uvaPf11nxeetFBlkrqOv40nd+UR6q0rpqnE=
branches:
  only:
  - stable
install: gem install jekyll
script:
- jekyll build
before_deploy:
- openssl aes-256-cbc -K $encrypted_3ecb93923dd4_key -iv $encrypted_3ecb93923dd4_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
addons:
  ssh_known_hosts: 69.163.163.106
sudo: false
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after _site/* $DEPLOY_USER@$DEPLOY_HOST:/home/barrosval/barrosval.me
  on:
    branch: stable
